### ISSUE TITLE
[BUG] h264_rtsp stream mode not working with Crowsnest

### ISSUE THREAD

**Issue by benholtz** [TheSpaghettiDetective/moonraker-obico#111]
**Description:**

I'm experiencing an issue where the h264_rtsp stream mode in the Obico Moonraker plugin is not working correctly when used in conjunction with Crowsnest.

**Steps to Reproduce:**

Enable RTSP in Crowsnest: 
Set `enable_rtsp = true` in the crowsnest.conf file.
Configure Obico: 
In moonraker-obico.cfg, set `stream_mode = h264_rtsp` and `rtsp_port = 8554` (or your custom RTSP port).
> [webcam]
> disable_video_streaming = False
> stream_mode = h264_rtsp
> rtsp_port = 8554

Restart Services: Restart Crowsnest, Moonraker, and Obico plugin.

**Expected Behavior:**

Obico should correctly read the RTSP stream from Crowsnest and display it in the Obico client.

**Actual Behavior:**
The following error appears in the Obico logs:

`2024-12-01 15:52:27,227     ERROR  obico.utils -
Traceback (most recent call last):
  File "/home/pi/moonraker-obico/moonraker_obico/webcam_stream.py", line 128, in start
    (janus_bin_path, ld_lib_path) = build_janus_config(webcams_to_build_janus_config, self.app_config.server.auth_token, JANUS_WS_PORT, JANUS_ADMIN_WS_PORT)
  File "/home/pi/moonraker-obico/moonraker_obico/janus_config_builder.py", line 282, in build_janus_config
    build_janus_plugin_streaming_jcfg(webcams)
  File "/home/pi/moonraker-obico/moonraker_obico/janus_config_builder.py", line 201, in build_janus_plugin_streaming_jcfg
    raise Exception('streaming_params.rtsp_port is required to do h264_rtsp streaming')`
This error suggests that the rtsp_port setting is not being correctly recognized or passed to the Janus configuration builder, even though it's present in the moonraker-obico.cfg file.

**System Information:**

Raspberry Pi: 4 Model B Rev 1.5
Operating System: Debian GNU/Linux 11 (bullseye)

**Additional Information:**

Code Analysis: Based on the Obico plugin's code, it appears that the rtsp_port setting is not explicitly handled when parsing the moonraker-obico.cfg file.
Workarounds: Modifying the code to manually set the RTSP port might be a temporary workaround, but a proper solution within the plugin would be preferred.

**Possible Solutions:**

Configuration Parsing: Update the configuration parsing logic to correctly read and utilize the rtsp_port setting from the [webcam] section in moonraker-obico.cfg.
Data Structures: Ensure that the internal data structures (e.g., the webcam object and its streaming_params) are correctly populated with the RTSP port when using the h264_rtsp mode.

**Request:**
Please investigate this issue and provide a solution that allows users to seamlessly use the h264_rtsp stream mode with Crowsnest without requiring code modifications or workarounds.

Thank you!

**Comment by kennethjiang** [comment]
I don't believe we support h264_rtsp. If you are using standard crowsnest configuration, you should just leave everything as default. 

For more info, you can consult this help page: https://www.obico.io/docs/user-guides/moonraker-obico/webcam/

In any case, this looks like a question not a code issue. You will get help a lot faster on our discord server: https://obico.io/discord/
