### ISSUE TITLE
Canceling print via Mainsail does not stop detection

### ISSUE THREAD

**Issue by raymondh2** [TheSpaghettiDetective/moonraker-obico#20]
Canceling print via Mainsail does not stop detection

**Comment by encetamasb** [comment]
@raymondh2 Please give me more context.

I tried to reproduce this, and I couldn't. Started print on app.thespaghettidetective.com, paused and cancelled it in mainsail. Print is cancelled in TSD too, and detective is not watching.

**Comment by raymondh2** [comment]
Seems to have been fixed.
