### ISSUE TITLE
Print progress percentage not showing

### ISSUE THREAD

**Issue by cryzzgrantham** [TheSpaghettiDetective/moonraker-obico#25]
Ive used this in my moonraker config

[virtual_sdcard]
path: home/pi/gcode_files

[display_status]

[pause_resume]

But I can't see the print progress or temprature status. Have I done something wrong or is this an issue? Previous post had a screenshot of his print % showing but no eta on finish, just seeing % and temptratures would be a great start for me. Any help is appreciated.

**Comment by kennethjiang** [comment]
Sorry for missing your issue! The print progress has not been implemented in moonraker-obico yet. Will work on that soon.

**Comment by raymondh2** [comment]
Duplicate of #24
