### ISSUE TITLE
Unable to print after first time printing for upload g-codes file

### ISSUE THREAD

**Issue by obs945** [TheSpaghettiDetective/moonraker-obico#33]
Since the tunnel function is not work for moonraker-obice that the only way is to upload G-codes to obico and printing afterward.
I tried upload G-codes for printing and the upload process is totally OK.
However, I found this is one-time function and I cannot print another gcode anymore.
After first time printing via obico uploaded g-codes, the status always showed "Operational" and always showed "Currently downing or printing!" after you pressed the start printing button.

**Comment by kennethjiang** [comment]
Fixed in 0.4.0
