### ISSUE TITLE
restart_action: moonraker-obico-.service' contains an invalid value

### ISSUE THREAD

**Issue by bweatherill** [TheSpaghettiDetective/moonraker-obico#36]
Having this issue on Moonraker. 

`[update_manager moonraker-obico]: Option 'restart_action: moonraker-obico-.service' contains an invalid value 'moonraker-obico-.service'. All values must be one of the following choices: ['moonraker-obico', 'klipper', 'moonraker']`

<img width="1597" alt="Screenshot 2022-07-13 at 18 12 39" src="https://user-images.githubusercontent.com/58088168/178792959-d918ffcd-342e-4e61-99fe-3d2f44268273.png">

I tried looking for the option 'Restart_action' but couldn't find anything. A member on Reddit had the same issue and fixed by removing -.service from managed services in moonraker-obico-update.cfg - Unfortunately this fix didn't work for me.

**Comment by kennethjiang** [comment]
Just released 0.4.2 that contains a fix for this bug. Please update to 0.4.2 and then run:

```
cd moonraker-obico && ./install.sh
```

When you are prompted to enter verification code, just press "enter" and quit. Then restart moonraker service. Feel free to re-open this issue, or come to obico.io/discord/ if it the problem persists.
