### ISSUE TITLE
Time Format Bug - Klipper w/ Moonraker

### ISSUE THREAD

**Issue by MaliciousCodez05** [TheSpaghettiDetective/moonraker-obico#39]
![Screenshot_20220811-004419](https://user-images.githubusercontent.com/111039397/184071108-798442e6-f1fc-4ed7-ba0e-105df816c8ce.png)

Running Obico version 1.66.120 : b187 on Android 12 and the latest versions of Klipper / moonraker-obico on mainsail. The top printer in the screenshot is running on Octoprint, but the bottom printer is running on the following versions of Klipper/Mainsail + Moonraker.

klipper
v0.10.0-546-ga709ba43

moonraker
v0.7.1-625-g413e3b2

moonraker-obico
v0.5.0-0-g574a741

mainsail
v2.2.1

Please let me know if I can help provide any additional information!

**Comment by kennethjiang** [comment]
Thanks! @MaliciousCodez05

**Comment by kennethjiang** [comment]
@MaliciousCodez05 This is fixed in 0.5.1.
