### ISSUE TITLE
Implement 25FPS Streaming on all architectures

### ISSUE THREAD

**Issue by raymondh2** [TheSpaghettiDetective/moonraker-obico#4]
Add Janus for 25 FPS streaming support for other architectures.
Support has been added for some 32 bit Pi images.

**Comment by Z3ytrox** [comment]
How do I add this?

**Comment by ulysnep** [comment]
Can we please get direction on how to implement this or get it on the roadmap please?

**Comment by raymondh2** [comment]
It has been implemented for some 32 bit raspberry pi images. Further support is pending backlog
