### ISSUE TITLE
Obico eating a lot of memory until pi die

### ISSUE THREAD

**Issue by appleimperio** [TheSpaghettiDetective/moonraker-obico#45]
ERROR  obico.utils - giving up on error: Janus quit! This should not happen. Exit code: 127
<img width="804" alt="Screen Shot 2022-09-12 at 2 09 26 PM" src="https://user-images.githubusercontent.com/72883739/189725888-123d6692-54b4-4756-83ce-dac88b9d8400.png">

I verified the H-top and is in fact moonraker-obico. Since I have it installed through kiauh I think that might be the problem I uninstalled and installed directly with the same result. The only reason that I can think of might be an issue is that im running klipper ,moonraker and obico in 1 pi and mainsail in another one.

**Comment by kennethjiang** [comment]
This is concerning.

Can you post an htop screenshot? Also does this happen when you are not printing?

**Comment by appleimperio** [comment]
Sorry I just uninstalled and it only happened when printing. I have a top screenshot but it doesn't show the obico service just read python3

**Comment by appleimperio** [comment]
I do two main things to resolve the issue. I don't know which one do the trick. First change the Pi from wifi to Ethernet and the other one since i have another pi running klipper but instead of using mjpeg streamer im using ustreamer. I change it to this one too, and it's working perfectly.
