### ISSUE TITLE
Cannot connect to moonraker

### ISSUE THREAD

**Issue by BoredFishRE** [TheSpaghettiDetective/moonraker-obico#75]
I'm using a mainsail install and I've tried to get obico working. It was working a few months ago, though it no longer works anymore. I install obico for moonraker, and link it to my account. The website acknowledges that it's linked, but it's on "Obico for Octoprint is offline".  I've uninstalled, relinked, and reinstalled so many times, but it always says it's offline. I'm at a loss now, and don't know what to do.

**Comment by kennethjiang** [comment]
Closing as we are addressing it in discord.
