### ISSUE TITLE
install on non pi device

### ISSUE THREAD

**Issue by Nazgile94** [TheSpaghettiDetective/moonraker-obico#80]
hi, i want to install moonraker-obico directly on my rooted creality k1 with moonraker+fluidd installed.

but the install.sh script is a bash script, and most klipper based printers just have sh.

any way to install moonraker-obico directly on my klipper printer  instead of a external raspberrypi?

**Comment by kennethjiang** [comment]
Closing as it's solved at https://www.reddit.com/r/crealityk1/comments/16n1ip8/comment/k2kcpi6/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by Nazgile94** [comment]
works, thanks!
