### ISSUE TITLE
Obico for Sovol SV07 Installation Guide

### ISSUE THREAD

**Issue by svmdevelopment** [TheSpaghettiDetective/moonraker-obico#81]
Installing Obico on my SV07 was taking quite some effort since not all required information was available in one place.
Hereby a short guide how it can be done:

First you need a program to connect to your Klipper server via SSH. I use PuTTY for that.
To SSH to your Klipper server you need to following login credentials: username _root_ with password _makerbase_
The hardware Klipper runs on has no RTC build in, that's why the time at the right hand corner is not shown correctly.
To install software on a Linux server (and thus on your Sovol SV07) you need to set the time to an approximate correct value.
Type the commando: _timedatectl set-time '2023-10-01 15:20:34'_ with the current time between single quotes.
Now execute the commands as by the installation guide of Obico.
During the installation the path to moonraker.conf  and to the logs directory will be requested (IP and port can be left as the default):
_/home/mks/printer_data/config/moonraker.conf
/home/mks/printer_data/logs_

Now the installation should be completed.

**Comment by kennethjiang** [comment]
Thank you @svmdevelopment for sharing this guide with us! Can you come to our discord channel https://www.obico.io/discord-obico-klipper/ to further discuss as I may need you to run a few commands to further simplify the installation process.
