### ISSUE TITLE
Qidi Xmax 3 error

### ISSUE THREAD

**Issue by rjacobsonjr** [TheSpaghettiDetective/moonraker-obico#87]
While doing this step: ./install.sh 
I'm getting this:
Cache entry deserialization failed, entry ignored
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Could not find a version that satisfies the requirement websocket-client==1.2.1 (from -r /home/mks/moonraker-obico/requirements.txt (line 1)) (from versions: )
No matching distribution found for websocket-client==1.2.1 (from -r /home/mks/moonraker-obico/requirements.txt (line 1))

**Comment by kennethjiang** [comment]
This is an environment issue. Not a bug. Go to our discord channel: https://obico.io/discord-obico-klipper/ to get help more quickly.

One community member solved this problem with this command `git config --global http.sslverify false`. But the obico team has not had a way to verify this fix.
