### ISSUE TITLE
 Cache entry deserialization failed, entry ignored

### ISSUE THREAD

**Issue by joshlacr43156** [TheSpaghettiDetective/moonraker-obico#88]
Hello all, 

I am attempting to install obico on my new Qidi X Max3, and have run into a problem with Step 4 of the Installation guide found at:

https://www.obico.io/blog/qidi-tech-x-series-klipper-remote-access-and-ai/

In the steps it states I will be prompted to fill in some information and I am being prompted to input that information and I am getting the error from the title. 

Any and all help is greatly appreciated, and I am sorry for my ignorance. Thanks in advance!

After running the installation line I receive this:

          ,----..
         /   /   \
        /   .     :    ,---,      ,--,
       .   /   ;.  \ ,---.'|    ,--.'|                  ,---.
      .   ;   /  ` ; |   | :    |  |,                  '   ,'\
      ;   |  ; \ ; | :   : :    `--'_        ,---.    /   /   |
      |   :  | ; | ' :     |,-. ,' ,'|      /     \  .   ; ,. :
      .   |  ' ' ' : |   : '  | '  | |     /    / '  '   | |: :
      '   ;  \; /  | |   |  / : |  | :    .    ' /   '   | .; :
       \   \  ',  /  '   : |: | '  : |__  '   ; :__  |   :    |
        ;   :    /   |   | '/ : |  | '.'| '   | '.'|  \   \  /
         \   \ .'    |   :    | ;  :    ; |   :    :   `----'
          `---`      /    \  /  |  ,   /   \   \  /
                     `-'----'    ---`-'     `----'

================> Obico for Klipper (Moonraker-Obico) <================
###                                                                 ###
=======================================================================

###### Installing required system packages... You may be prompted to enter password.

[sudo] password for mks:
Get:1 http://security.debian.org buster/updates InRelease [34.8 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:3 http://mirrors.jevincanders.net/armbian/apt buster InRelease [52.7 kB]
Get:5 http://deb.debian.org/debian buster-backports InRelease [51.4 kB]
Get:6 http://security.debian.org buster/updates/main arm64 Packages [745 kB]
Get:7 http://security.debian.org buster/updates/main armhf Packages [749 kB]
Get:8 http://security.debian.org buster/updates/non-free arm64 Packages [6,166 B]
Get:9 http://security.debian.org buster/updates/non-free armhf Packages [11.3 kB]
Get:10 http://deb.debian.org/debian buster/non-free arm64 Packages [64.2 kB]
Get:11 http://deb.debian.org/debian buster/main armhf Packages [10.5 MB]
Get:12 http://mirrors.jevincanders.net/armbian/apt buster/main all Packages [87.6 kB]
Get:13 http://mirrors.jevincanders.net/armbian/apt buster/buster-utils all Packages [23.3 kB]
Get:14 http://mirrors.jevincanders.net/armbian/apt buster/buster-desktop armhf Packages [36.7 kB]
Get:15 http://mirrors.jevincanders.net/armbian/apt buster/buster-utils armhf Packages [68.6 kB]
Get:16 http://mirrors.jevincanders.net/armbian/apt buster/buster-utils arm64 Packages [115 kB]
Get:17 http://mirrors.jevincanders.net/armbian/apt buster/main arm64 Packages [800 kB]
Get:18 http://deb.debian.org/debian buster/main arm64 Packages [10.5 MB]
Get:19 http://mirrors.jevincanders.net/armbian/apt buster/buster-desktop arm64 Packages [35.9 kB]
Get:20 http://mirrors.jevincanders.net/armbian/apt buster/main armhf Packages [457 kB]
Get:21 http://mirrors.jevincanders.net/armbian/apt buster/buster-desktop all Packages [11.7 kB]
Get:22 http://deb.debian.org/debian buster/non-free armhf Packages [74.5 kB]
Get:23 http://deb.debian.org/debian buster-updates/main arm64 Packages.diff/Index [12.1 kB]
Get:24 http://deb.debian.org/debian buster-updates/main armhf Packages.diff/Index [12.1 kB]
Get:25 http://deb.debian.org/debian buster-backports/non-free armhf Packages.diff/Index [27.8 kB]
Get:26 http://deb.debian.org/debian buster-backports/contrib arm64 Packages.diff/Index [27.8 kB]
Get:27 http://deb.debian.org/debian buster-backports/non-free arm64 Packages.diff/Index [27.8 kB]
Get:28 http://deb.debian.org/debian buster-backports/main arm64 Packages.diff/Index [27.8 kB]
Get:29 http://deb.debian.org/debian buster-backports/main armhf Packages.diff/Index [27.8 kB]
Get:30 http://deb.debian.org/debian buster-updates/main arm64 Packages 2022-08-18-2019.35.pdiff [283 B]
Get:30 http://deb.debian.org/debian buster-updates/main arm64 Packages 2022-08-18-2019.35.pdiff [283 B]
Get:31 http://deb.debian.org/debian buster-updates/main armhf Packages 2022-08-18-2019.35.pdiff [283 B]
Get:31 http://deb.debian.org/debian buster-updates/main armhf Packages 2022-08-18-2019.35.pdiff [283 B]
Get:32 http://deb.debian.org/debian buster-backports/non-free armhf Packages 2022-09-15-0222.33.pdiff [217 B]
Get:32 http://deb.debian.org/debian buster-backports/non-free armhf Packages 2022-09-15-0222.33.pdiff [217 B]
Get:33 http://deb.debian.org/debian buster-backports/contrib arm64 Packages 2022-09-15-0222.33.pdiff [472 B]
Get:33 http://deb.debian.org/debian buster-backports/contrib arm64 Packages 2022-09-15-0222.33.pdiff [472 B]
Get:34 http://deb.debian.org/debian buster-backports/non-free arm64 Packages 2022-09-15-0222.33.pdiff [10.5 kB]
Get:35 http://deb.debian.org/debian buster-backports/non-free arm64 Packages 2022-09-22-1115.32.pdiff [42 B]
Get:35 http://deb.debian.org/debian buster-backports/non-free arm64 Packages 2022-09-22-1115.32.pdiff [42 B]
Get:36 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-08-06-0203.55.pdiff [3,377 B]
Get:37 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-09-04-0825.07.pdiff [1,510 B]
Get:38 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-09-15-0222.33.pdiff [295 B]
Get:39 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-09-15-1403.46.pdiff [16.5 kB]
Get:40 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-09-22-1115.32.pdiff [89 B]
Get:41 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-10-11-2005.54.pdiff [430 B]
Get:42 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-10-12-0205.44.pdiff [270 B]
Get:43 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-10-25-0803.25.pdiff [15.5 kB]
Get:44 http://deb.debian.org/debian buster-backports/main arm64 Packages 2022-11-05-1403.42.pdiff [315 B]
Get:45 http://deb.debian.org/debian buster-backports/main arm64 Packages 2023-08-30-1418.39.pdiff [754 B]
Get:46 http://deb.debian.org/debian buster-backports/main arm64 Packages 2023-10-02-2009.11.pdiff [858 B]
Get:47 http://deb.debian.org/debian buster-backports/main arm64 Packages 2023-11-02-0803.41.pdiff [818 B]
Get:48 http://deb.debian.org/debian buster-backports/main arm64 Packages 2023-12-08-0205.50.pdiff [836 B]
Get:49 http://deb.debian.org/debian buster-backports/main arm64 Packages 2024-01-17-1406.13.pdiff [1,968 B]
Get:49 http://deb.debian.org/debian buster-backports/main arm64 Packages 2024-01-17-1406.13.pdiff [1,968 B]
Get:50 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-08-06-0807.18.pdiff [3,962 B]
Get:51 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-09-04-0825.07.pdiff [201 B]
Get:52 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-09-15-0222.33.pdiff [292 B]
Get:53 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-09-16-0203.01.pdiff [16.8 kB]
Get:54 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-09-22-1115.32.pdiff [82 B]
Get:55 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-10-11-2005.54.pdiff [430 B]
Get:56 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-10-12-0205.44.pdiff [267 B]
Get:57 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-10-25-0803.25.pdiff [15.5 kB]
Get:58 http://deb.debian.org/debian buster-backports/main armhf Packages 2022-11-05-1403.42.pdiff [317 B]
Get:59 http://deb.debian.org/debian buster-backports/main armhf Packages 2023-08-30-1418.39.pdiff [756 B]
Get:60 http://deb.debian.org/debian buster-backports/main armhf Packages 2023-10-02-2009.11.pdiff [858 B]
Get:61 http://deb.debian.org/debian buster-backports/main armhf Packages 2023-11-02-0803.41.pdiff [818 B]
Get:62 http://deb.debian.org/debian buster-backports/main armhf Packages 2023-12-08-0205.50.pdiff [836 B]
Get:63 http://deb.debian.org/debian buster-backports/main armhf Packages 2024-01-17-1406.13.pdiff [1,942 B]
Get:63 http://deb.debian.org/debian buster-backports/main armhf Packages 2024-01-17-1406.13.pdiff [1,942 B]
Fetched 24.9 MB in 16s (1,543 kB/s)
Reading package lists... Done
N: Repository 'http://security.debian.org buster/updates InRelease' changed its 'Suite' value from 'oldstable' to 'oldoldstable'
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.12' to '10.13'
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'oldstable' to 'oldoldstable'
N: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'oldstable-updates' to 'oldoldstable-updates'
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-virtualenv is already the newest version (15.1.0+ds-2+deb10u1).
python3 is already the newest version (3.7.3-1).
python3 set to manually installed.
The following additional packages will be installed:
  libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3
  libswscale5 libwebpmux3
Suggested packages:
  ffmpeg-doc
Recommended packages:
  python3-setuptools python3-wheel
The following NEW packages will be installed:
  python3-pip
The following packages will be upgraded:
  ffmpeg libavcodec58 libavdevice58 libavfilter7 libavformat58 libavresample4 libavutil56 libpostproc55 libswresample3
  libswscale5 libwebpmux3
11 upgraded, 1 newly installed, 0 to remove and 230 not upgraded.
Need to get 8,953 kB of archives.
After this operation, 697 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main arm64 python3-pip all 18.1-5 [171 kB]
Get:2 http://security.debian.org buster/updates/main arm64 ffmpeg arm64 7:4.1.11-0+deb10u1 [1,433 kB]
Get:3 http://security.debian.org buster/updates/main arm64 libavdevice58 arm64 7:4.1.11-0+deb10u1 [129 kB]
Get:4 http://security.debian.org buster/updates/main arm64 libavfilter7 arm64 7:4.1.11-0+deb10u1 [964 kB]
Get:5 http://security.debian.org buster/updates/main arm64 libswscale5 arm64 7:4.1.11-0+deb10u1 [189 kB]
Get:6 http://security.debian.org buster/updates/main arm64 libavformat58 arm64 7:4.1.11-0+deb10u1 [965 kB]
Get:7 http://security.debian.org buster/updates/main arm64 libavcodec58 arm64 7:4.1.11-0+deb10u1 [4,459 kB]
Get:8 http://security.debian.org buster/updates/main arm64 libswresample3 arm64 7:4.1.11-0+deb10u1 [107 kB]
Get:9 http://security.debian.org buster/updates/main arm64 libpostproc55 arm64 7:4.1.11-0+deb10u1 [93.9 kB]
Get:10 http://security.debian.org buster/updates/main arm64 libavresample4 arm64 7:4.1.11-0+deb10u1 [100 kB]
Get:11 http://security.debian.org buster/updates/main arm64 libavutil56 arm64 7:4.1.11-0+deb10u1 [245 kB]
Get:12 http://security.debian.org buster/updates/main arm64 libwebpmux3 arm64 0.6.1-2+deb10u3 [97.2 kB]
Fetched 8,953 kB in 3s (3,228 kB/s)
(Reading database ... 147515 files and directories currently installed.)
Preparing to unpack .../00-ffmpeg_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking ffmpeg (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../01-libavdevice58_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavdevice58:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../02-libavfilter7_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavfilter7:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../03-libswscale5_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libswscale5:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../04-libavformat58_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavformat58:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../05-libavcodec58_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavcodec58:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../06-libswresample3_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libswresample3:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../07-libpostproc55_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libpostproc55:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../08-libavresample4_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavresample4:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../09-libavutil56_7%3a4.1.11-0+deb10u1_arm64.deb ...
Unpacking libavutil56:arm64 (7:4.1.11-0+deb10u1) over (7:4.1.9-0+deb10u1) ...
Preparing to unpack .../10-libwebpmux3_0.6.1-2+deb10u3_arm64.deb ...
Unpacking libwebpmux3:arm64 (0.6.1-2+deb10u3) over (0.6.1-2+deb10u1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../11-python3-pip_18.1-5_all.deb ...
Unpacking python3-pip (18.1-5) ...
Setting up libavutil56:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libpostproc55:arm64 (7:4.1.11-0+deb10u1) ...
Setting up python3-pip (18.1-5) ...
Setting up libswscale5:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libwebpmux3:arm64 (0.6.1-2+deb10u3) ...
Setting up libswresample3:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libavresample4:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libavcodec58:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libavformat58:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libavfilter7:arm64 (7:4.1.11-0+deb10u1) ...
Setting up libavdevice58:arm64 (7:4.1.11-0+deb10u1) ...
Setting up ffmpeg (7:4.1.11-0+deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10+deb10u1) ...
###### Creating python virtual environment for moonraker-obico...

Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/mks/moonraker-obico-env/bin/python3
Also creating executable in /home/mks/moonraker-obico-env/bin/python
Installing setuptools, pip, wheel...done.
  Cache entry deserialization failed, entry ignored
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1056)'))': /simple/websocket-client/
  Could not find a version that satisfies the requirement websocket-client==1.2.1 (from -r /home/mks/moonraker-obico/requirements.txt (line 1)) (from versions: )
No matching distribution found for websocket-client==1.2.1 (from -r /home/mks/moonraker-obico/requirements.txt (line 1))

**Comment by kennethjiang** [comment]
This is an environment issues. Our github issues are reserved for reporting code bugs.

Please go to https://obico.io/discord-obico-klipper/. You will get more prompt help there.
