### ISSUE TITLE
Minnor fix for Creality K1

### ISSUE THREAD

**Issue by Guilouz** [TheSpaghettiDetective/moonraker-obico#89]
https://github.com/TheSpaghettiDetective/moonraker-obico/blob/42d764e70b1c6279e1f0242348ee839894557a66/scripts/install_creality.sh#L33

Can you replace opkg commands in Creality K1 script by /opt/bin/opkg

To avoid ./scripts/install_creality.sh: line 33: opkg: not found

After firmware update Entware is partially uninstalled but all the binaries remain available and functional and users do not think about reinstalling Entware and end up with this kind of error.

See: https://github.com/Guilouz/Creality-K1-and-K1-Max/discussions/329

**Comment by kennethjiang** [comment]
Fixed in https://github.com/TheSpaghettiDetective/moonraker-obico/commit/17266d590e128bb6952fcd7c03541f744efad0ff

Thank you for bringing this up to me @Guilouz I would have never encountered this edge case myself! :)
