### ISSUE TITLE
[BUG] armbian buster repository has not Release file

### ISSUE THREAD

**Issue by niko0d** [TheSpaghettiDetective/moonraker-obico#91]
Can not complete obico install.
Moonraker TimeLapse have same issue:
https://github.com/mainsail-crew/moonraker-timelapse/issues/156

Err:6 http://fi.mirror.armbian.de/apt buster Release
  404  Not Found [IP: 65.21.120.247 80]
Reading package lists... Done
E: The repository 'http://apt.armbian.com buster Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by kennethjiang** [comment]
Closed in https://github.com/TheSpaghettiDetective/moonraker-obico/commit/ff4d9b93f56489329d0756d7c35c089259aa1acd
